import {readFile,writeFile,mkdir} from 'node:fs/promises';
const c=JSON.parse(await readFile('dist/content.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const ext='target="_blank" rel="noopener noreferrer"';
const nav=[['','Home'],['videos','Vídeos'],['downloads','Downloads'],['sobre','Sobre'],['contato','Contato']];
const card=(v,i)=>`<a class="video-card" href="https://www.youtube.com/watch?v=${esc(v.id)}" ${ext}><div class="thumbnail"><img src="${esc(v.thumbnail)}" alt="" width="720" height="405" loading="lazy"><span class="play" aria-hidden="true">▶</span><span class="duration">${esc(v.duration)}</span></div><p class="video-label">CRÔNICA ${String(i+1).padStart(2,'0')} <span>YOUTUBE ↗</span></p><h3>${esc(v.title)}</h3><dl class="video-context"><div><dt>${esc(v.gameLabel||'Jogo')}</dt><dd>${esc(v.game)}</dd></div><div><dt>${esc(v.thinker?(v.referenceLabel||'Pensador'):'Tema')}</dt><dd>${esc(v.thinker||v.theme)}</dd></div></dl></a>`;
const title=(k,h,p)=>`<section class="page-title"><p class="eyebrow">${k}</p><h1>${h}</h1><p>${p}</p></section>`;
const milestone=`<section class="journey"><div><p class="eyebrow">A JORNADA CONTINUA</p><h2>Uma ideia de cada vez.<br>Uma crônica de cada vez.</h2><p>Desde 6 de junho de 2026, explorando o que existe além da tela.</p><a class="text-link" href="/sobre/">Conheça a história do projeto ↗</a></div><div class="goal">100<span>VÍDEOS · A PRÓXIMA CONQUISTA</span></div></section>`;
const latest=c.videos[0];
const home=`<section class="hero"><div class="hero-copy"><p class="eyebrow">JOGOS, HISTÓRIA E FILOSOFIA</p><h1>Todo jogo conta<br>uma história.<br><em>Toda história<br>esconde uma ideia.</em></h1><p class="intro">Videoensaios para enxergar além da superfície. Entre mundos virtuais e perguntas que continuam com a gente.</p><a class="button" href="/videos/">Encontre sua próxima crônica <span>↗</span></a></div><div class="featured"><div class="feature-kicker"><span>EM DESTAQUE</span><span>APERTE O PLAY ↘</span></div><a href="https://www.youtube.com/watch?v=${latest.id}" ${ext}><div class="thumbnail"><img src="${esc(latest.thumbnail)}" alt="Miniatura: ${esc(latest.title)}" width="720" height="405"><span class="play" aria-hidden="true">▶</span><span class="duration">${latest.duration}</span></div><p class="eyebrow">POKÉMON · MEMÓRIA · MISTÉRIO</p><h2>${esc(latest.title)}</h2><span class="text-link">Assistir no YouTube ↗</span></a></div></section><div class="channel-banner"><img src="${esc(c.banner)}" width="2560" height="424" alt="Banner oficial GRS Crônicas, com um corredor liminar e o nome do canal em letras pixeladas"></div><section class="latest"><div class="section-heading"><div><p class="eyebrow">ALÉM DA TELA</p><h2>Outras histórias. Novas perguntas.</h2></div><a class="text-link" href="/videos/">Todos os vídeos ↗</a></div><div class="video-grid">${c.videos.slice(1,4).map(card).join('')}</div></section><section class="translation-callout"><div><p class="eyebrow">DO INGLÊS PARA O PORTUGUÊS</p><h2>Menos barreiras.<br>Mais histórias para viver.</h2></div><div><p>As traduções de jogos feitas pelo GRS Crônicas vão ganhar uma casa por aqui.</p><a class="button secondary" href="/downloads/">Explore as traduções ↗</a></div></section>${milestone}`;
const videos=title('O ARQUIVO DE CRÔNICAS','O jogo termina.<br><em>A reflexão continua.</em>','Filosofia, história e cultura pop se encontram nos mundos que a gente joga.')+`<section class="all-videos"><div class="archive-line"><span>${c.videos.length} VIDEOENSAIOS NO ARQUIVO</span><a href="${c.youtube}/videos" ${ext}>Visitar o canal ↗</a></div><div class="video-grid">${c.videos.map(card).join('')}</div></section>`;
const downloads=title('TRADUÇÕES · PT-BR','Histórias sem<br><em>barreira de idioma.</em>','Traduções de jogos originalmente em inglês, feitas pelo GRS Crônicas.')+(c.downloads.length?`<section class="downloads">${c.downloads.map(d=>{const url=new URL(d.url);if(url.protocol!=='https:')throw Error('Download precisa de HTTPS');return `<article class="empty-download"><span class="file-symbol" aria-hidden="true">PT<br>BR</span><div><h2>${esc(d.title)}</h2><p>${esc(d.description)}</p><a class="button" href="${esc(url.href)}" ${ext}>Baixar tradução ↗</a></div></article>`;}).join('')}</section>`:`<section class="empty-download"><span class="file-symbol" aria-hidden="true">PT<br>BR</span><div><p class="eyebrow">EM PREPARAÇÃO</p><h2>Um espaço para novas histórias.</h2><p>Os arquivos ainda não estão disponíveis. Quando uma tradução for publicada, você encontrará aqui o download, a versão compatível e as instruções de instalação.</p><a class="text-link" href="${c.youtube}" ${ext}>Acompanhe o projeto no YouTube ↗</a></div></section>`);
const about=title('SOBRE O PROJETO','Enxergar além<br><em>da superfície.</em>','Todo jogo conta uma história. Toda história esconde uma ideia.')+`<section class="about-grid"><div class="about-brand"><img src="${esc(c.avatar)}" width="300" height="300" alt="Marca oficial GRS Crônicas"><p>GRS CRÔNICAS<br><span>DESDE 06.06.2026</span></p></div><div class="about-copy"><p>O GRS Crônicas começou em <strong>6 de junho de 2026</strong>, como um espaço para conectar jogos, história e filosofia.</p><p>Nos videoensaios, jogos, filmes, desenhos e cultura pop abrem caminho para conversar sobre filosofia, história, sociologia e perguntas que atravessam gerações. De um corredor vazio em um jogo ao peso de uma escolha, sempre existe algo para olhar mais de perto.</p><p>Este site reúne os vídeos do canal e vai receber as traduções de jogos que faço, para que mais pessoas possam acompanhar essas histórias em português.</p><h2>A meta atual: 100 vídeos postados.</h2><p>Uma jornada construída publicação por publicação, com curiosidade para descobrir a próxima ideia escondida em uma história.</p><a class="button" href="${c.youtube}" ${ext}>Faça parte dessa jornada ↗</a></div></section>`;
const contact=title('CONTATO','A conversa continua<br><em>fora do jogo.</em>','Para acompanhar as crônicas, trocar ideias ou falar sobre o projeto.')+`<section class="contacts">${[['01','YouTube','Os videoensaios completos',c.youtube],['02','Instagram','Crônicas e reflexões em outros formatos',c.instagram],['03','TikTok','Uma nova crônica a cada vídeo',c.tiktok],['04','X / Twitter','Ideias e conversas além dos vídeos',c.x],['05','Twitch','Acompanhe o canal na Twitch',c.twitch],['06','E-mail',c.email,'mailto:'+c.email]].map(([n,label,desc,url])=>`<a href="${esc(url)}" ${label==='E-mail'?'':ext}><span class="contact-number">${n}</span><div><h2>${label}</h2><p>${esc(desc)}</p></div><span class="contact-arrow">↗</span></a>`).join('')}</section>`;
const pages={'':home,videos,downloads,sobre:about,contato:contact};
for(const [slug,label] of nav){const path=slug?`dist/${slug}`:'dist';await mkdir(path,{recursive:true});const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1112"><title>${label==='Home'?'GRS Crônicas — Jogos, história e filosofia':label+' — GRS Crônicas'}</title><meta name="description" content="${esc(label==='Home'?'Todo jogo conta uma história. Toda história esconde uma ideia. Videoensaios e traduções do GRS Crônicas.':label+' do GRS Crônicas: jogos, história e filosofia.')}"><link rel="icon" href="${esc(c.avatar)}"><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><header><a class="brand" href="/" aria-label="GRS Crônicas — Home"><img src="${esc(c.avatar)}" alt="" width="56" height="56"><span>GRS <b>CRÔNICAS</b></span></a><nav aria-label="Navegação principal">${nav.map(([s,l])=>`<a href="/${s?s+'/':''}" ${s===slug?'aria-current="page"':''}>${l}</a>`).join('')}</nav><a class="channel-link" href="${c.youtube}" ${ext}>▶ <span>YouTube</span></a></header><main id="conteudo">${pages[slug]}</main><footer><a class="footer-brand" href="/">GRS CRÔNICAS<span>Jogos, história e filosofia.</span></a><div><a href="${c.youtube}" ${ext}>YouTube ↗</a><a href="${c.instagram}" ${ext}>Instagram ↗</a><a href="${c.tiktok}" ${ext}>TikTok ↗</a><a href="${c.x}" ${ext}>X / Twitter ↗</a><a href="${c.twitch}" ${ext}>Twitch ↗</a></div><a href="mailto:${c.email}">${c.email}</a></footer></body></html>`;await writeFile(`${path}/index.html`,html);}
